#!/bin/bash

check_shebang() {
    # Reads the first two bytes to check for '#!'
    if [[ $(head -c 2 "$1") == '#!' ]]; then
        # Extracts the interpreter path
        interpreter=$(head -n 1 "$1" | cut -c 3-)
        echo "$(basename "$1"): $interpreter"
    fi
}

if [ "$#" -eq 0 ]; then
    # No arguments: check all files in the current directory
    for file in *; do
        if [ -f "$file" ]; then
            check_shebang "$file"
        fi
    done | sort
else
    # With arguments: check each argument
    for arg in "$@"; do
        if [ -f "$arg" ]; then
            # It's a file
            check_shebang "$arg"
        elif [ -d "$arg" ]; then
            # It's a directory
            for file in "$arg"/*; do
                if [ -f "$file" ]; then
                    check_shebang "$file"
                fi
            done
        fi
    done | sort
fi